def init():
    global PARAM
    PARAM = {
        'data_name': {'train': 'WikiText2', 'test': 'WikiText2'},
        'model_name': 'basic',
        'control_name': 'GRU_200_200_5_0.9_0_0',
        'special_TAG': '',
        'optimizer_name': 'SGD',
        'scheduler_name': 'CosineAnnealingLR',
        'patience': 1,
        'lr': 1,
        'weight_decay': 1e-6,
        'milestones': [150, 250],
        'threshold': 1e-4,
        'threshold_mode': 'rel',
        'factor': 0.25,
        'clip': 0.25,
        'bptt': 35,
        'batch_size': {'train': 80, 'validation':80, 'test': 80},
        'num_workers': 0,
        'data_size': {'train': 0, 'test': 0},
        'device': 'cuda',
        'num_epochs': 100,
        'save_mode': 0,
        'world_size': 1,
        'metric_names': {'train': ['perplexity'], 'validation':['perplexity'], 'test': ['perplexity']},
        'init_seed': 0,
        'num_Experiments': 1,
        'tuning_param': {'nlp': 1},
        'activation': 'tanh',
        'resume_mode': 0
    }
