
def init():
    global PARAM
    PARAM = {
        'data_name': {'train':'UCID_patch','test':'Kodak'},
        'model_name': 'codec',
        'control_name': '8_8',
        'special_TAG': '',
        'optimizer_name': 'Adam',
        'scheduler_name': 'ReduceLROnPlateau',
        'lr': 1e-4,
        'weight_decay': 0,
        'milestones': [150,225],
        'threshold': 1e-3,
        'threshold_mode': 'rel',
        'factor': 0.5,
        'batch_size': {'train':100,'test':1},
        'num_workers': 0,
        'data_size': {'train':0,'test':0},
        'device': 'cuda',
        'num_epochs': 300,
        'save_mode': 0,
        'world_size': 1,
        'metric_names': {'train':['psnr'],'test':['bpp','psnr','mssim']},
        'topk': 1,
        'init_seed': 0,
        'num_Experiments': 1,
        'tuning_param': {'compression': 1, 'classification': 0},
        'loss_mode': {'compression':'mse','classification':'ce'},
        'normalization': 'none',
        'activation': 'relu',
        'img_size': (128,128),
        'show': True,
        'resume_mode': 0
    }